language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - cd sichu
  - python manage.py test --with-coverage
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
