from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    'cabinet.views',
    url(r'^index/$', 'index'),
    url(r'^register/$', 'register'),
    url(r'^chg_personal_info/$', 'chg_personal_info'),
    url(r'^chg_pwd/$', 'chg_pwd'),
    url(r'^send_test_mail/$', 'send_test_mail'),
    url(r'^add_book/$', 'add_book'),
    url(r'^user/(?P<uid>\d+)/$', 'show_user'),
    url(r'^v2/user/(?P<uid>\d+)/$', 'show_user_v2'),
    url(r'^book/(?P<bid>\d+)/$', 'book_info'),
    url(r'^v2/book/(?P<bid>\d+)/$', 'book_info_v2'),
    url(r'^bookownership/(?P<boid>\d+)/$', 'show_bookownership'),
    url(r'^edit_bookownership/$', 'edit_bookownership'),
    url(r'^del_bookownership/$', 'del_bookownership'),
    url(r'^ebook_request/$', 'ebook_request'),
    url(r'^sys_msgs/$', 'sys_msgs'),
    url(r'^get_dlg/$', 'get_dlg'),
    url(r'^borrow_request/$', 'borrow_request'),
    url(r'^borrow_accept/$', 'borrow_accept'),
    url(r'^return_book/$', 'return_book'),
    url(r'^search/$', 'search'),
    url(r'^del_ebook_request/$', 'del_ebook_request'),
    url(r'^repos/$', 'repos'),
    url(r'^create_repo/$', 'create_repo'),
    url(r'^other_repos/$', 'other_repos'),
    url(r'^repo_apply/$', 'repo_apply'),
    url(r'^join_repo_process/$', 'join_repo_process'),
    url(r'^repo/(?P<rid>\d+)/$', 'show_repo'),
    url(r'^books/latest/(?P<page>\d+)/$', 'books_latest'),
    url(r'^books/mybooks/(?P<page>\d+)/$', 'books_mybooks'),
    url(r'^books/loaned/(?P<page>\d+)/$', 'books_loaned'),
    url(r'^books/borrowed/(?P<page>\d+)/$', 'books_borrowed'),
    url(r'^books/wanted/(?P<page>\d+)/$', 'books_wanted'),
    url(r'^books/wish/(?P<page>\d+)/$', 'books_wish'),
    url(r'^books/userbook_(?P<uid>\d+)/(?P<page>\d+)/$', 'userbook'),
    url(r'^v2/books/userbook_(?P<uid>\d+)/(?P<page>\d+)/$', 'userbook_v2'),
    url(r'^books/userwanted_(?P<uid>\d+)/(?P<page>\d+)/$', 'userwanted'),
    url(r'^v2/books/userwanted_(?P<uid>\d+)/(?P<page>\d+)/$', 'userwanted_v2'),
    url(r'^mybookshelf/$', 'mybookshelf'),
    url(r'^personal_info/$', 'personal_info'),
    url(r'^check_isbn/$', 'check_isbn'),
    url(r'^book_want/$', 'book_want'),
    url(r'^wishlist/$', 'wishlist'),
    url(r'^del_bookwant/$', 'del_bookwant'),
    url(r'^following/$', 'following'),
    url(r'^following/del/$', 'following_del'),
    url(r'^friends/$', 'friends'),
    url(r'^help/$', 'help'),
    url(r'^email_verify/$', 'email_verify'),
    )
